### PR TITLE
Add ability to execute against development storage account.

### PR DESCRIPTION
**Pull request by jonathanstowell**
Ability to run the Tasks against the Azure Storage Emulator.

### CODE REVIEW

**Comment by phillipsj** [comment]
@jonathanstowell I apologize for not having noticing this sooner.  I need to fix my notifications, I am going to check this over in the morning and accept it.  Nice contribution.

**Comment by Philo** [comment]
@phillipsj - this merge doesnt appear to be released onto nuget?

**Comment by phillipsj** [comment]
@Philo going to go this out the door tomorrow.  I have been out with a new baby.

**Comment by phillipsj** [comment]
@Philo @jonathanstowell @JRKelso Can someone test this out to make sure it behaves as expected, once I get a thumps up I will release.  

#addin nuget:https://www.myget.org/F/beta-builds/api/v2?package=Cake.AzureStorage&prerelease

**Comment by Philo** [comment]
@phillipsj - Unfortunately I have moved away from using this addin at the moment as it doesnt support setting the content type for uploaded blobs, all uploaded files are stored as application/octet-stream which causes various issues depending on how the blob storage container is used.

I will add this as an issue/feature request.

**Pull request merged**
